openapi: 3.0.0
info:
  description: Model Engine API for Causemos.
  version: "1.0"
  title: Causemos Modeling Engine API
paths:
  # Create model
  /create-model:
    post:
      summary: Create a new model
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ModelCreationRequest"
        description: Create a new model by providng the INDRA statements and node/edge parameters
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ModelCreationResponse"

  # Status
  /models/{modelId}:
    parameters:
      - $ref: "#/components/parameters/modelId"
    get: 
      summary: Returns model status
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ModelCreationResponse"

  # Experiments
  /models/{modelId}/experiments:
    parameters:
      - $ref: "#/components/parameters/modelId"
    post:
      summary: Invoke an experiment. The payload varies deends on the experiment type, which can be one of [PROJECTION, SENSITIVITY]. This should return immediately with a designated experimentId while the actual experiment runs in the background
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/ProjectionParameters'
                - $ref: '#/components/schemas/SensitivityAnalysisParameters'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  experimentId:
                    type: string
                    format: uuid

  # Experiment
  /models/{modelId}/experiments/{experimentId}:
    parameters:
      - $ref: "#/components/parameters/modelId"
      - $ref: "#/components/parameters/experimentId"
    get:
      summary: Retrieves the state and result of a modeling experiment.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/ProjectionResponse'
                  - $ref: '#/components/schemas/SensitivityAnalysisResponse'

  # Update model
  /models/{modelId}/edit-indicators:
    parameters:
      - $ref: "#/components/parameters/modelId"
    post:
      summary: Update indicator specification for a set of nodes
      requestBody:
        content:
          application/json:
            schema:
              type: string
      responses:
        "200":
          description: OK

  # Update model
  /models/{modelId}/edit-edges:
    parameters:
      - $ref: "#/components/parameters/modelId"
    post:
      summary: Edit edge weight values
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/EditEdgesRequest'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EditEdgesResponse'

        
components:
  parameters:
    modelId:
      name: modelId
      in: path
      description: UUID of a Causemos Model
      required: true
      schema:
        type: string
        format: uuid
    experimentId:
      name: experimentId
      in: path
      description: UUID of a Causemos Model Experiment
      required: true
      schema:
        type: string
        format: uuid

  schemas:
    # Basic reusable timeseries
    TimeSeries:
      type: array
      items:
        type: object
        properties:
          timestamp:
            type: number
          value:
            type: number

    # For create-model
    ModelCreationRequest:
      type: object
      properties:
        id:
          type: string
          description: A Causemos model UUID
        statements:
          type: array
          description: Causemos INDRA statement
          items:
            type: object
        conceptIndicators:
          type: object
          description: Node parameters
          properties:
            <conceptName>:
              type: object
              description: Concept node name
              properties:
                name:
                  type: string
                func:
                  type: string
                numLevels:
                  type: number
                values:
                  allOf:
                    - $ref: '#/components/schemas/TimeSeries'
    ModelCreationResponse:
      type: object
      properties:
        status:
          type: string
        conceptIndicators:
          type: object
          properties:
            <conceptName>:
              type: object
              properties:
                initialValue:
                  type: number
                scalingFactor:
                  type: number
                  description: optional, provided if engine supports y-scaling
                scalingBias:
                  type: number
                  description: optional, provided if engine supports y-scaling
        relations:
          type: array
          items:
            type: object
            properties:
              source:
                type: string
              target:
                type: string
              weights:
                type: array
                items:
                  type: number

    ModelExperimentCreationRequest:
      type: object
      properties:
        experimentType:
          type: string
          enum: ["PROJECTION", "SENSITIVITY_ANALYSIS"]
    
    ProjectionParameters:
      allOf:
        - $ref: '#/components/schemas/ModelExperimentCreationRequest'
        - type: object
          properties: 
            experimentParams:
              type: object
              properties:
                startTime:
                  type: number
                timeStepsInMonths:
                  type: number
                constraints:
                  type: array
                  items:
                    type: object
                    properties:
                      concept:
                        type: string
                      value:
                        type: array
                        items:
                          type: object
                          properties:
                            step:
                              type: number
                            value:
                              type: number
    
    SensitivityAnalysisParameters:
      allOf:
        - $ref: '#/components/schemas/ModelExperimentCreationRequest'
        - type: object
          properties: 
            experimentParams:
              type: object
              properties:
                startTime:
                  type: number
                endTime:
                  type: number
                numTimesteps:
                  type: number
                analysisType:
                  type: string
                  enum: ["IMMEDIATE", "GLOBAL", "PATHWAYS"]
                analysisMode:
                  type: string
                  enum: ["STATIC", "DYNAMIC"]
                analysisParam:
                  type: object
                  properties:
                    source:
                      type: array
                      items:
                        type: string
                    target:
                      type: array
                      items:
                        type: string
                    pathAtt:
                      type: string
                      enum: ["INFLUENCE", "SENSITIVITY"]
                    numPath:
                      type: number

    ModelExperimentStatusResponse:
      type: object
      properties:
        modelId:
          type: string
          format: uuid
        experimentId:
          type: string
          format: uuid
        experimentType:
          type: string
          enum: ["PROJECTION", "SENSITIVITY_ANALYSIS"]
        status:
          type: string
          enum: ["Completed", "In Progress"]
        
    ProjectionResponse:
      allOf:
        - $ref: '#/components/schemas/ModelExperimentStatusResponse'
        - type: object
          properties:
            results:
              type: array
              items:
                type: object
                properties:
                  concept:
                    type: string
                  values:
                    allOf:
                      - $ref: '#/components/schemas/TimeSeries'
                  confidenceInterval:
                    type: object
                    properties:
                      upper:
                        allOf:
                          - $ref: '#/components/schemas/TimeSeries'
                      lower:
                        allOf:
                          - $ref: '#/components/schemas/TimeSeries'
    
    SensitivityAnalysisResponse:
      allOf:
        - $ref: '#/components/schemas/ModelExperimentStatusResponse'
        - type: object
          properties:
            immediate:
              type: object
              properties:
                source:
                  type: array
                  items:
                    type: string
                target:
                  type: array
                  items:
                    type: string
                value:
                  type: array
                  items:
                    type: number
            global:
              type: object
              properties:
                source:
                  type: array
                  items:
                    type: string
                target:
                  type: array
                  items:
                    type: string
                value:
                  type: array
                  items:
                    type: number
            pathways:
              type: object
              properties:
                path:
                  type: array
                  items:
                    type: string
                score:
                  type: number

    EditEdgesRequest:
      type: object
      properties:
        relations:
          type: array
          items:
            type: object
            properties:
              source:
                type: string
              target:
                type: string
              weights:
                type: array
                items:
                  type: number
    
    EditEdgesResponse:
      type: object
      properties:
        status:
          type: string
